### ISSUE TITLE
Problems running with Rhythmbox 3.4.2, Ubuntu 18.04.6 LTS 64-bit

### ISSUE THREAD

**Issue by GlenKPeterson** [TheBigW/ParametricEQ#12]
I installed like this:
```
cd ~/.local/share/rhythmbox/plugins/
git clone https://github.com/TheBigW/ParametricEQ.git
```

Then I started Rhythmbox from the command line.
These happen even without plugin installed:
```
$ rhythmbox

(rhythmbox:28391): Gtk-CRITICAL **: 16:49:00.350: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(rhythmbox:28391): Gtk-WARNING **: 16:49:00.352: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:28391): Gtk-WARNING **: 16:49:00.352: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)
```

With this plugin installed, I also get this when I try to configure it (and it crashes):
```
(rhythmbox:28391): libpeas-CRITICAL **: 16:49:10.811: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed

(rhythmbox:28391): libpeas-WARNING **: 16:49:25.406: Error importing plugin 'ParametricEQ':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gpeterso/.local/share/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 22, in <module>
    from Equalizer import EQControl
  File "/home/gpeterso/.local/share/rhythmbox/plugins/ParametricEQ/Equalizer.py", line 19, in <module>
    from ParametricEQconfig import Config
  File "/home/gpeterso/.local/share/rhythmbox/plugins/ParametricEQ/ParametricEQconfig.py", line 19, in <module>
    from gi.repository import GConf
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GConf, introspection typelib not found

(rhythmbox:28391): libpeas-WARNING **: 16:49:25.406: Error loading plugin 'ParametricEQ'

(rhythmbox:28391): libpeas-CRITICAL **: 16:49:25.407: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed
^C
```

**Comment by TheBigW** [comment]
Hi Glen,

this may be a very poor response: I recognized a while ago that in newer Linux releases GConf seems not to be installed by default any more. Unfortunately I always still got it working, so never got rid of GConf in the code ... Here I what I found in my bash history:

git clone https://github.com/TheBigW/ParametricEQ.git
rhythmbox
sudo apt install gconf gconf2
sudo apt install gconf2
sudo apt install python-gconf
sudo apt install python-gc
rhythmbox
sudo apt install python3-gconf
rhythmbox
sudo apt install gir1.2-gconf-2.0
rhythmbox

I would walk up backwards - my guess is that this solved it for me :). I don't exactly recall; this was probably a year ago. I probably should invest some time to clean this up some time ... maybe latest once GConf is finally gone for good and I can't work around it anymore ... or at some point fix the install for the plugin and update the dependencies...
