### ISSUE TITLE
various errors on launch of rhythmbox

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/ParametricEQ#9]
Just compiling the latest code and started rhythmbox.

Noticed the following errors - apart from the index issue there are lots of threads being generated.  Expected?

<pre>
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 177, in do_activate
    ParametricEQPlugin.pulseVolumeCheckTimer(self)
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 140, in pulseVolumeCheckTimer
    pulseVolume = int(allVolumes[1])
IndexError: list index out of range

(rhythmbox:33483): GLib-GObject-CRITICAL **: g_object_new_valist: object class 'RBSourceToolbar' has no property named 'margin-start'

(rhythmbox:33483): GLib-GObject-CRITICAL **: g_object_new_valist: object class 'RBSourceToolbar' has no property named 'margin-start'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 140, in pulseVolumeCheckTimer
    pulseVolume = int(allVolumes[1])
IndexError: list index out of range

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 140, in pulseVolumeCheckTimer
    pulseVolume = int(allVolumes[1])
IndexError: list index out of range

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 140, in pulseVolumeCheckTimer
    pulseVolume = int(allVolumes[1])
IndexError: list index out of range
</pre>

**Comment by TheBigW** [comment]
ohh my ... one of those things that felt dirty and actually are dirty. I used a self resetting timer to poll the global system volume. Seems python threading.Timer starts a new thread each time... should have read the docs before..
I replaced it now with a single thread suspendedly polling each 2 seconds. Just submitted. he index out of range maybe due to inability to call pactl which is part of pulseaudio-utils. I did not find a better way to get the global system volume.

**Comment by fossfreedom** [comment]
thanks - that has fixed the continuous spewing of error messages.

I still see the first index error above on startup but the equalizer seems to be working now:

<pre>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 52, in run
    PullVolumeThread.pulseVolumeCheckTimer(self.eqInst)
  File "/usr/lib/rhythmbox/plugins/ParametricEQ/ParametricEQ.py", line 79, in pulseVolumeCheckTimer
    pulseVolume = int(allVolumes[1])
IndexError: list index out of range
</pre>

**Comment by TheBigW** [comment]
thanks for fast feedback, but it only is not continuous any more and so the loudness correction feature won't work in your case. The thread would just abort at first failure.

Can you please post me the output of 'pactl list sinks'. I guess my hard-coded approach that works for me was maybe just too optimistic....

**Comment by fossfreedom** [comment]
http://paste.ubuntu.com/10874400/

**Comment by TheBigW** [comment]
thanks that helped a lot. I just submitted an update. Hard coded selection at index 1 was probably not the wisest choice... I now select the last device volume I find. That works for plugged in USB devices that pop up at the end as well as for only build in as in your case.
